<a href="https://colab.research.google.com/github/tjdux/pandas-for-finance/blob/main/01_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Series 만드는 방법

In [35]:
import pandas as pd

In [36]:
# Data Type: list
ls1= [1, 2, 3, 4, 5, 6, 7, 8, 9]
ls2 = [1, 2, 3, "Apple", "play", 6, 7, 8, 9]

sr1 = pd.Series(ls1)
sr1

sr2 = pd.Series(ls2)
sr2

0        1
1        2
2        3
3    Apple
4     play
5        6
6        7
7        8
8        9
dtype: object

In [37]:
# Series에 Name 설정
sr1.name = "Number"
sr2.name = "Word"
sr1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: Number, dtype: int64

In [38]:
# DataType: dictionary
dic1 = {"a": 1, "b": 2, "c": 3}
sr3 = pd.Series(dic1)
sr3.name = "Number"
sr3

a    1
b    2
c    3
Name: Number, dtype: int64

## CSV 파일을 Series로 불러오기

In [39]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [40]:
file_path = "/content/drive/MyDrive/financial pandas/삼성전자 종가.csv"
df = pd.read_csv(file_path, index_col=0, header=0)
samsung_price = df.squeeze(axis=1) # DataFrame -> Series
type(samsung_price)

pandas.core.series.Series

## Index & Value

In [41]:
samsung_price.index

Index(['2018-01-02', '2018-01-03', '2018-01-04', '2018-01-05', '2018-01-08',
       '2018-01-09', '2018-01-10', '2018-01-11', '2018-01-12', '2018-01-15',
       ...
       '2021-12-06', '2021-12-07', '2021-12-08', '2021-12-09', '2021-12-10',
       '2021-12-13', '2021-12-14', '2021-12-15', '2021-12-16', '2021-12-17'],
      dtype='object', name='Date', length=977)

In [42]:
# 2020-12-15 데이터가 있을까?
print('2020-12-15' in samsung_price.index)
print(samsung_price.loc['2020-12-15'])

True
73800

In [43]:
# 100번째 Data값?
print(samsung_price.iloc[100])

49500

## 새로운 값 추가

In [44]:
# samsung_price의 총 길이?
print(samsung_price.shape)
print(f"마지막 인덱스: {samsung_price.index[samsung_price.shape[0]-1]}")

(977,)
마지막 인덱스: 2021-12-17

In [45]:
# 2021-12-20 가격 업데이트
samsung_price.loc["2021-12-20"] = 77100
samsung_price.tail()

Date
2021-12-14    77000
2021-12-15    77600
2021-12-16    77800
2021-12-17    78000
2021-12-20    77100
Name: Close, dtype: int64

## 두 개의 Series 연결하기

In [46]:
file_path = "/content/drive/MyDrive/financial pandas/samsung_excel.xlsx"
series1_samsung = pd.read_excel(file_path, index_col=0, header=0,
                                sheet_name="Sheet1").squeeze()
series2_samsung = pd.read_excel(file_path, index_col=0, header=0,
                                sheet_name="Sheet2").squeeze()
series_samsung = pd.concat([series1_samsung, series2_samsung], ignore_index=False)
series_samsung

Date
2018-01-02    51020
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...
2021-12-20    77100
2021-12-21    78100
2021-12-22    79400
2021-12-23    79900
2021-12-24    80500
Name: Close, Length: 982, dtype: int64

## 기본 통계치 구하기

In [47]:
print(f"고점: {samsung_price.max()}")
print(f"저점: {samsung_price.min()}")

고점: 91000
저점: 37450

In [48]:
samsung_price.describe()

count      978.000000
mean     57316.104294
std      14091.429092
min      37450.000000
25%      46300.000000
50%      51300.000000
75%      70200.000000
max      91000.000000
Name: Close, dtype: float64

In [49]:
# 고점인 날짜
print(f"{samsung_price.index[samsung_price.values == samsung_price.max()]}")
print(f"{samsung_price.index[samsung_price.argmax()]}")
print(f"{samsung_price.iloc[samsung_price.argmax()]}")

Index(['2021-01-11'], dtype='object', name='Date')
2021-01-11
91000

## Series 연산

In [50]:
samsung_price.shift().head()

Date
2018-01-02        NaN
2018-01-03    51020.0
2018-01-04    51620.0
2018-01-05    51080.0
2018-01-08    52120.0
Name: Close, dtype: float64

In [51]:
# 삼성전자 수익률
samsung_return = (samsung_price - samsung_price.shift()) / samsung_price.shift()
samsung_return.head()

Date
2018-01-02         NaN
2018-01-03    0.011760
2018-01-04   -0.010461
2018-01-05    0.020360
2018-01-08   -0.001919
Name: Close, dtype: float64

In [52]:
samsung_price.pct_change().head()

Date
2018-01-02         NaN
2018-01-03    0.011760
2018-01-04   -0.010461
2018-01-05    0.020360
2018-01-08   -0.001919
Name: Close, dtype: float64

In [53]:
# 수익률이 제일 높은 날짜
samsung_return.index[samsung_return.argmax()]

'2020-03-24'

## NaN값 처리
- NaN값 제거: `dropna()`
- NaN값 채우기: `fillna()`
- NaN값 연산: 결과 `NaN`

In [54]:
samsung_return.head()

Date
2018-01-02         NaN
2018-01-03    0.011760
2018-01-04   -0.010461
2018-01-05    0.020360
2018-01-08   -0.001919
Name: Close, dtype: float64

In [55]:
samsung_return.dropna().head()

Date
2018-01-03    0.011760
2018-01-04   -0.010461
2018-01-05    0.020360
2018-01-08   -0.001919
2018-01-09   -0.031142
Name: Close, dtype: float64

In [56]:
samsung_return.fillna(0).head()

Date
2018-01-02    0.000000
2018-01-03    0.011760
2018-01-04   -0.010461
2018-01-05    0.020360
2018-01-08   -0.001919
Name: Close, dtype: float64

## 순서대로 정렬
- `sort_values(ascending=True or False)`
- `sort_index(ascending=True or False)`

In [57]:
samsung_price.sort_index(ascending=False).head()

Date
2021-12-20    77100
2021-12-17    78000
2021-12-16    77800
2021-12-15    77600
2021-12-14    77000
Name: Close, dtype: int64

In [58]:
samsung_price.sort_values().head()

Date
2019-01-04    37450
2019-01-03    37600
2019-01-08    38100
2018-12-27    38250
2018-12-26    38350
Name: Close, dtype: int64

In [59]:
samsung_price.sort_values(ascending=False).head(1)

Date
2021-01-11    91000
Name: Close, dtype: int64

## 특정 조건에 맞는 값을 찾고 싶을 때
- `Series.values or index [조건]`

In [60]:
import numpy as np

In [61]:
samsung_return_percentage = samsung_return * 100
samsung_return_percentage.head()

Date
2018-01-02         NaN
2018-01-03    1.176009
2018-01-04   -1.046106
2018-01-05    2.036022
2018-01-08   -0.191865
Name: Close, dtype: float64

In [64]:
samsung_return_percentage[samsung_return_percentage.values >= 4]

Date
2018-03-06     4.026549
2018-09-14     4.086266
2018-11-02     4.744958
2019-03-21     4.086266
2020-03-20     5.704307
2020-03-24    10.470588
2020-04-17     4.897959
2020-06-03     6.031128
2020-06-16     4.408818
2020-07-28     5.395683
2020-11-16     4.905063
2020-11-23     4.327666
2020-12-24     5.277402
2021-01-08     7.117008
2021-02-25     4.024390
2021-11-22     5.196629
2021-12-01     4.347826
Name: Close, dtype: float64

In [65]:
samsung_return_percentage.index[samsung_return_percentage.values >= 4]

Index(['2018-03-06', '2018-09-14', '2018-11-02', '2019-03-21', '2020-03-20',
       '2020-03-24', '2020-04-17', '2020-06-03', '2020-06-16', '2020-07-28',
       '2020-11-16', '2020-11-23', '2020-12-24', '2021-01-08', '2021-02-25',
       '2021-11-22', '2021-12-01'],
      dtype='object', name='Date')

In [69]:
samsung_return_percentage[samsung_return_percentage.values >= 4]
sum(samsung_return_percentage.values >= 4)

np.int64(17)

In [72]:
samsung_return_over_4 = pd.Series(np.where(samsung_return_percentage.values >= 4, 1, 0))
samsung_return_over_4.index = samsung_return.index
samsung_return_over_4

Date
2018-01-02    0
2018-01-03    0
2018-01-04    0
2018-01-05    0
2018-01-08    0
             ..
2021-12-14    0
2021-12-15    0
2021-12-16    0
2021-12-17    0
2021-12-20    0
Length: 978, dtype: int64