<a href="https://colab.research.google.com/github/tjdux/pandas-for-finance/blob/main/02_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## DataFrame 만들기

In [1]:
import pandas as pd

In [2]:
ls = ["a", "b", "c", "d", "e"]
ls_df = pd.DataFrame(ls, index=["ㄱ", "ㄴ", "ㄷ", "ㄹ", "ㅁ"], columns=["알파벳"])
ls_df

  알파벳
ㄱ   a
ㄴ   b
ㄷ   c
ㄹ   d
ㅁ   e

In [3]:
dic = {"영수": 101, "영철": 102, "영삼": 103, "영자": 104, "영호": 105}
dic_df = pd.DataFrame(dic, index=["학번"])
dic_df

     영수   영철   영삼   영자   영호
학번  101  102  103  104  105

In [4]:
dic_df = pd.DataFrame(dic.values())
dic_df.index = dic.keys()
dic_df.columns = ["성적"]
dic_df

     성적
영수  101
영철  102
영삼  103
영자  104
영호  105

## DataFrame으로 데이터 불러오기

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
lotte_che_df = pd.read_csv("/content/drive/MyDrive/financial pandas/롯데케미칼.csv", index_col="Date", header=0)
lotte_che_df

              Open    High     Low   Close  Volume    Change
Date
2018-01-02  368000  370000  360500  360500   92533 -0.020380
2018-01-03  360000  368500  360000  363000   81340  0.006935
2018-01-04  367500  367500  349000  349000  190391 -0.038567
2018-01-05  351000  352000  348000  351500   99268  0.007163
2018-01-08  359000  383500  358000  383500  490208  0.091038
...            ...     ...     ...     ...     ...       ...
2021-12-16  233000  234000  224500  228000  144647 -0.012987
2021-12-17  227000  235000  226500  234500  138945  0.028509
2021-12-20  232000  233500  228000  229500   90630 -0.021322
2021-12-21  232000  232500  227000  229500   98669  0.000000
2021-12-22  229000  230000  225000  225000   99419 -0.019608

[980 rows x 6 columns]

## 행과 열 선택하기
- **⭐DataFrame 열이름 선택할 때 내가 출력할 값을 Series로 할지, DataFrame으로 할지 명확하게 파악해야 함**

In [7]:
print(type(lotte_che_df.loc["2018-01-02"]))
print(type(lotte_che_df.loc[["2018-01-02"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [8]:
print(type(lotte_che_df.loc["2021-12-16":]))

<class 'pandas.core.frame.DataFrame'>

In [9]:
print(type(lotte_che_df.iloc[0]))
print(type(lotte_che_df.iloc[[0]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [10]:
lotte_che_df.iloc[[0, 10, 100]]

              Open    High     Low   Close  Volume    Change
Date
2018-01-02  368000  370000  360500  360500   92533 -0.020380
2018-01-16  398000  400000  388000  395000   88807 -0.013733
2018-05-30  371000  376500  361500  363000  107516 -0.026810

In [11]:
print(type(lotte_che_df["Open"]))
print(type(lotte_che_df[["Open"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [12]:
lotte_che_df[lotte_che_df.columns[[0, 2, 5]]].head()

              Open     Low    Change
Date
2018-01-02  368000  360500 -0.020380
2018-01-03  360000  360000  0.006935
2018-01-04  367500  349000 -0.038567
2018-01-05  351000  348000  0.007163
2018-01-08  359000  358000  0.091038

## DataFrame 행과 열 추가하기

In [13]:
#lotte_che = lotte_che_df[["Open", "High", "Low", "Close", "Volume"]]
lotte_che = lotte_che_df[lotte_che_df.columns[:-1]]
lotte_che.head()

              Open    High     Low   Close  Volume
Date
2018-01-02  368000  370000  360500  360500   92533
2018-01-03  360000  368500  360000  363000   81340
2018-01-04  367500  367500  349000  349000  190391
2018-01-05  351000  352000  348000  351500   99268
2018-01-08  359000  383500  358000  383500  490208

In [14]:
# 행 추가
lotte_che["Return"] = lotte_che["Close"].pct_change().fillna(0)
lotte_che.head()

              Open    High     Low   Close  Volume    Return
Date
2018-01-02  368000  370000  360500  360500   92533  0.000000
2018-01-03  360000  368500  360000  363000   81340  0.006935
2018-01-04  367500  367500  349000  349000  190391 -0.038567
2018-01-05  351000  352000  348000  351500   99268  0.007163
2018-01-08  359000  383500  358000  383500  490208  0.091038

In [15]:
# 열 추가
lotte_che.loc["2021-12-23"] = [100, 200, 300, 400, 500, 600]
lotte_che.tail(1)

            Open  High  Low  Close  Volume  Return
Date
2021-12-23   100   200  300    400     500   600.0

## DataFrame 행과 열 예제

In [16]:
def return_fn(df):
  df_close = df[["Close"]]
  df_close["Return"] = df_close["Close"].pct_change().fillna(0)
  return df_close

In [17]:
res = return_fn(lotte_che_df)
res.head()

/tmp/ipykernel_2527/2648756716.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_close["Return"] = df_close["Close"].pct_change().fillna(0)

             Close    Return
Date
2018-01-02  360500  0.000000
2018-01-03  363000  0.006935
2018-01-04  349000 -0.038567
2018-01-05  351500  0.007163
2018-01-08  383500  0.091038

## DataFrame 합치기
- `pd.concat([dataframe1, dataframe2], keys=[], names=[], axix=0|1, join="outer"|"inner")`
- index의 타입이 같아야 함

In [18]:
df_samsung = pd.read_excel("/content/drive/MyDrive/financial pandas/samsung_naver_excel.xlsx", sheet_name="samsung", index_col=0)
df_samsung.head()

             Open   High    Low  Close  Volume    Change
Date
2018-01-02  51380  51400  50780  51020  169485  0.001177
2018-01-03  52540  52560  51420  51620  200270  0.011760
2018-01-04  52120  52180  50640  51080  233909 -0.010461
2018-01-05  51300  52120  51200  52120  189623  0.020360
2018-01-08  52400  52520  51500  52020  167673 -0.001919

In [19]:
df_naver = pd.read_excel("/content/drive/MyDrive/financial pandas/samsung_naver_excel.xlsx", sheet_name="naver", index_col=0)
df_naver.head()

              Open    High     Low   Close  Volume    Change
Date
2016-01-04  130182  131784  126578  126579   93272 -0.039511
2016-01-05  126778  128580  126378  127580   69456  0.007908
2016-01-06  129181  129181  124575  124776   95682 -0.021978
2016-01-07  125377  132187  125377  130585  125253  0.046555
2016-01-08  130585  131987  128582  130585   63922  0.000000

In [20]:
# axis=0
df = pd.concat([df_samsung, df_naver])
print(df.shape)
print(df_samsung.shape[0] + df_naver.shape[0] == df.shape[0])

(1717, 6)
True

In [21]:
df = pd.concat([df_samsung, df_naver], keys=["naver", "samsung"], names=["stock", "date"])
df.head()

                   Open   High    Low  Close  Volume    Change
stock date
naver 2018-01-02  51380  51400  50780  51020  169485  0.001177
      2018-01-03  52540  52560  51420  51620  200270  0.011760
      2018-01-04  52120  52180  50640  51080  233909 -0.010461
      2018-01-05  51300  52120  51200  52120  189623  0.020360
      2018-01-08  52400  52520  51500  52020  167673 -0.001919

In [22]:
print(df.index)
print(df.loc[[("naver", "2018-01-02")]])

MultiIndex([(  'naver', '2018-01-02'),
            (  'naver', '2018-01-03'),
            (  'naver', '2018-01-04'),
            (  'naver', '2018-01-05'),
            (  'naver', '2018-01-08'),
            (  'naver', '2018-01-09'),
            (  'naver', '2018-01-10'),
            (  'naver', '2018-01-11'),
            (  'naver', '2018-01-12'),
            (  'naver', '2018-01-15'),
            ...
            ('samsung', '2019-12-16'),
            ('samsung', '2019-12-17'),
            ('samsung', '2019-12-18'),
            ('samsung', '2019-12-19'),
            ('samsung', '2019-12-20'),
            ('samsung', '2019-12-23'),
            ('samsung', '2019-12-24'),
            ('samsung', '2019-12-26'),
            ('samsung', '2019-12-27'),
            ('samsung', '2019-12-30')],
           names=['stock', 'date'], length=1717)
                   Open   High    Low  Close  Volume    Change
stock date
naver 2018-01-02  51380  51400  50780  51020  169485  0.001177

In [23]:
# axis=1, join="inner"

df = pd.concat([df_samsung, df_naver], keys=["naver", "samsung"], names=["stock", "date"], axis=1, join="inner")
df.head()

stock       naver                                        samsung          \
date         Open   High    Low  Close  Volume    Change    Open    High
Date
2018-01-02  51380  51400  50780  51020  169485  0.001177  174447  177251
2018-01-03  52540  52560  51420  51620  200270  0.011760  175448  177051
2018-01-04  52120  52180  50640  51080  233909 -0.010461  176048  179653
2018-01-05  51300  52120  51200  52120  189623  0.020360  178852  183858
2018-01-08  52400  52520  51500  52020  167673 -0.001919  183258  190869

stock
date           Low   Close  Volume    Change
Date
2018-01-02  174247  177251   93587  0.017240
2018-01-03  173045  174447   84790 -0.015819
2018-01-04  174847  178853  130112  0.025257
2018-01-05  176249  181857  136811  0.016796
2018-01-08  181856  190269  196338  0.046256

In [24]:
# DataFrame 3개 합치기
# index 타입이 달라 inner join 해도 shape 0
df = pd.concat([df_samsung, df_naver, lotte_che_df], keys=["samsung", "naver", "lotte"], names=["stock", "date"], axis=1, join="inner")
print(f"df.shape: {df.shape}")
print(f"df_samsung.index: {type(df_samsung.index)}")
print(f"df_naver.index: {type(df_naver.index)}")
print(f"lotte_che_df.index: {type(lotte_che_df.index)}")

df.shape: (0, 18)
df_samsung.index: <class 'pandas.core.indexes.datetimes.DatetimeIndex'>
df_naver.index: <class 'pandas.core.indexes.datetimes.DatetimeIndex'>
lotte_che_df.index: <class 'pandas.core.indexes.base.Index'>

## DataFrame Index Type
- DataFrame 합칠 때 주의사항!

In [25]:
print(f"df_samsung.index[0]: {type(df_samsung.index[0])}")
print(f"df_naver.index[0]: {type(df_naver.index[0])}")
print(f"lotte_che_df.index[0]: {type(lotte_che_df.index[0])}")

df_samsung.index[0]: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
df_naver.index[0]: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
lotte_che_df.index[0]: <class 'str'>

In [26]:
lotte_che_df.index = pd.to_datetime(lotte_che_df.index)
print(f"lotte_che_df.index: {type(lotte_che_df.index)}")
print(f"lotte_che_df.index[0]: {type(lotte_che_df.index[0])}")

lotte_che_df.index: <class 'pandas.core.indexes.datetimes.DatetimeIndex'>
lotte_che_df.index[0]: <class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [27]:
df = pd.concat([df_samsung, df_naver, lotte_che_df], keys=["samsung", "naver", "lotte"], names=["stock", "date"], axis=1, join="inner")
df.head()

stock      samsung                                          naver          \
date          Open   High    Low  Close  Volume    Change    Open    High
Date
2018-01-02   51380  51400  50780  51020  169485  0.001177  174447  177251
2018-01-03   52540  52560  51420  51620  200270  0.011760  175448  177051
2018-01-04   52120  52180  50640  51080  233909 -0.010461  176048  179653
2018-01-05   51300  52120  51200  52120  189623  0.020360  178852  183858
2018-01-08   52400  52520  51500  52020  167673 -0.001919  183258  190869

stock                                          lotte                          \
date           Low   Close  Volume    Change    Open    High     Low   Close
Date
2018-01-02  174247  177251   93587  0.017240  368000  370000  360500  360500
2018-01-03  173045  174447   84790 -0.015819  360000  368500  360000  363000
2018-01-04  174847  178853  130112  0.025257  367500  367500  349000  349000
2018-01-05  176249  181857  136811  0.016796  351000  352000  348000  351500
2018-01-08  181856  190269  196338  0.046256  359000  383500  358000  383500

stock
date        Volume    Change
Date
2018-01-02   92533 -0.020380
2018-01-03   81340  0.006935
2018-01-04  190391 -0.038567
2018-01-05   99268  0.007163
2018-01-08  490208  0.091038

## NaN
- `df.isna()`
- `df.dropna()`
- `df.fillna(value)`

In [42]:
df = pd.concat([df_samsung, df_naver, lotte_che_df], keys=["samsung", "naver", "lotte"], names=["stock", "date"], axis=1, join="outer")

df_samsung_close = df[[('samsung',  'Close')]]
df_samsung_close

stock      samsung
date         Close
Date
2016-01-04     NaN
2016-01-05     NaN
2016-01-06     NaN
2016-01-07     NaN
2016-01-08     NaN
...            ...
2021-12-16     NaN
2021-12-17     NaN
2021-12-20     NaN
2021-12-21     NaN
2021-12-22     NaN

[1469 rows x 1 columns]

In [43]:
df_samsung_close.isna().sum()

stock    date
samsung  Close    731
dtype: int64

In [44]:
df_samsung_close.dropna().isna().sum()

stock    date
samsung  Close    0
dtype: int64

In [46]:
df_samsung_close.fillna(0).isna().sum()

stock    date
samsung  Close    0
dtype: int64

In [58]:
# NaN 값에 해당되는 날짜만 찾기
df_samsung_close[df_samsung_close.isna().values].index

DatetimeIndex(['2016-01-04', '2016-01-05', '2016-01-06', '2016-01-07',
               '2016-01-08', '2016-01-11', '2016-01-12', '2016-01-13',
               '2016-01-14', '2016-01-15',
               ...
               '2021-12-09', '2021-12-10', '2021-12-13', '2021-12-14',
               '2021-12-15', '2021-12-16', '2021-12-17', '2021-12-20',
               '2021-12-21', '2021-12-22'],
              dtype='datetime64[ns]', name='Date', length=731, freq=None)

## `info()`, `describe()`

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1469 entries, 2016-01-04 to 2021-12-22
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (samsung, Open)    738 non-null    float64
 1   (samsung, High)    738 non-null    float64
 2   (samsung, Low)     738 non-null    float64
 3   (samsung, Close)   738 non-null    float64
 4   (samsung, Volume)  738 non-null    float64
 5   (samsung, Change)  738 non-null    float64
 6   (naver, Open)      979 non-null    float64
 7   (naver, High)      979 non-null    float64
 8   (naver, Low)       979 non-null    float64
 9   (naver, Close)     979 non-null    float64
 10  (naver, Volume)    979 non-null    float64
 11  (naver, Change)    979 non-null    float64
 12  (lotte, Open)      980 non-null    float64
 13  (lotte, High)      980 non-null    float64
 14  (lotte, Low)       980 non-null    float64
 15  (lotte, Close)     980 non-null    float64
 16  (lotte, Volume)    980 non-null    float64
 17  (lotte, Change)    980 non-null    float64
dtypes: float64(18)
memory usage: 218.1 KB

In [63]:
df.describe()

stock       samsung                                                          \
date           Open          High           Low         Close        Volume
count    738.000000    738.000000    738.000000    738.000000  7.380000e+02
mean   50000.460705  50533.481030  49458.523035  50216.869919  1.361474e+07
std     7702.675480   7820.644455   7631.618287   7055.377470  9.439103e+06
min        0.000000      0.000000      0.000000  37450.000000  0.000000e+00
25%    45262.500000  45900.000000  44900.000000  45500.000000  8.077088e+06
50%    48680.000000  49200.000000  48000.000000  48745.000000  1.199751e+07
75%    53600.000000  53900.000000  52875.000000  53500.000000  1.775210e+07
max    79000.000000  81300.000000  78200.000000  81000.000000  6.349111e+07

stock                      naver                                               \
date       Change           Open           High            Low          Close
count  738.000000     979.000000     979.000000     979.000000     979.000000
mean     0.000784  147904.304392  149774.075587  145962.802860  148274.173647
std      0.017700   20766.399720   20897.664784   20573.241066   19056.913614
min     -0.063877       0.000000       0.000000       0.000000  106500.000000
25%     -0.009950  132544.000000  134500.000000  130441.500000  133000.000000
50%      0.001065  151412.000000  153500.000000  149811.000000  151214.000000
75%      0.010629  162230.000000  164000.000000  160426.500000  162029.000000
max      0.104706  189068.000000  195275.000000  186865.000000  192272.000000

stock                                    lotte                                \
date         Volume      Change           Open           High            Low
count  9.790000e+02  979.000000     980.000000     980.000000     980.000000
mean   2.208698e+05    0.000545  270290.816327  274691.836735  265755.102041
std    2.856504e+05    0.019582   67071.213030   67905.088593   66068.051743
min    0.000000e+00   -0.067706  121000.000000  143000.000000  114500.000000
25%    7.384250e+04   -0.010662  223500.000000  226375.000000  219500.000000
50%    1.083110e+05    0.000000  265500.000000  269000.000000  262000.000000
75%    2.941180e+05    0.010373  299625.000000  304000.000000  293625.000000
max    5.304519e+06    0.139241  474500.000000  475000.000000  463500.000000

stock
date           Close        Volume      Change
count     980.000000  9.800000e+02  980.000000
mean   269804.081633  1.881471e+05   -0.000144
std     66937.798972  2.816061e+05    0.026984
min    117000.000000  4.348100e+04   -0.155235
25%    223000.000000  1.030385e+05   -0.013799
50%    265000.000000  1.483915e+05   -0.001410
75%    299000.000000  2.241755e+05    0.012306
max    474500.000000  8.154268e+06    0.260684