<a href="https://colab.research.google.com/github/tjdux/pandas-for-finance/blob/main/02_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## DataFrame 만들기

In [14]:
import pandas as pd

In [15]:
ls = ["a", "b", "c", "d", "e"]
ls_df = pd.DataFrame(ls, index=["ㄱ", "ㄴ", "ㄷ", "ㄹ", "ㅁ"], columns=["알파벳"])
ls_df

  알파벳
ㄱ   a
ㄴ   b
ㄷ   c
ㄹ   d
ㅁ   e

In [16]:
dic = {"영수": 101, "영철": 102, "영삼": 103, "영자": 104, "영호": 105}
dic_df = pd.DataFrame(dic, index=["학번"])
dic_df

     영수   영철   영삼   영자   영호
학번  101  102  103  104  105

In [17]:
dic_df = pd.DataFrame(dic.values())
dic_df.index = dic.keys()
dic_df.columns = ["성적"]
dic_df

     성적
영수  101
영철  102
영삼  103
영자  104
영호  105

## DataFrame으로 데이터 불러오기

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:
lotte_che_df = pd.read_csv("/content/drive/MyDrive/financial pandas/롯데케미칼.csv", index_col="Date", header=0)
lotte_che_df

              Open    High     Low   Close  Volume    Change
Date
2018-01-02  368000  370000  360500  360500   92533 -0.020380
2018-01-03  360000  368500  360000  363000   81340  0.006935
2018-01-04  367500  367500  349000  349000  190391 -0.038567
2018-01-05  351000  352000  348000  351500   99268  0.007163
2018-01-08  359000  383500  358000  383500  490208  0.091038
...            ...     ...     ...     ...     ...       ...
2021-12-16  233000  234000  224500  228000  144647 -0.012987
2021-12-17  227000  235000  226500  234500  138945  0.028509
2021-12-20  232000  233500  228000  229500   90630 -0.021322
2021-12-21  232000  232500  227000  229500   98669  0.000000
2021-12-22  229000  230000  225000  225000   99419 -0.019608

[980 rows x 6 columns]

## 행과 열 선택하기
- **⭐DataFrame 열이름 선택할 때 내가 출력할 값을 Series로 할지, DataFrame으로 할지 명확하게 파악해야 함**

In [20]:
print(type(lotte_che_df.loc["2018-01-02"]))
print(type(lotte_che_df.loc[["2018-01-02"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [21]:
print(type(lotte_che_df.loc["2021-12-16":]))

<class 'pandas.core.frame.DataFrame'>

In [22]:
print(type(lotte_che_df.iloc[0]))
print(type(lotte_che_df.iloc[[0]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [23]:
lotte_che_df.iloc[[0, 10, 100]]

              Open    High     Low   Close  Volume    Change
Date
2018-01-02  368000  370000  360500  360500   92533 -0.020380
2018-01-16  398000  400000  388000  395000   88807 -0.013733
2018-05-30  371000  376500  361500  363000  107516 -0.026810

In [24]:
print(type(lotte_che_df["Open"]))
print(type(lotte_che_df[["Open"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [25]:
lotte_che_df[lotte_che_df.columns[[0, 2, 5]]].head()

              Open     Low    Change
Date
2018-01-02  368000  360500 -0.020380
2018-01-03  360000  360000  0.006935
2018-01-04  367500  349000 -0.038567
2018-01-05  351000  348000  0.007163
2018-01-08  359000  358000  0.091038

## DataFrame 행과 열 추가하기

In [27]:
#lotte_che = lotte_che_df[["Open", "High", "Low", "Close", "Volume"]]
lotte_che = lotte_che_df[lotte_che_df.columns[:-1]]
lotte_che.head()

              Open    High     Low   Close  Volume
Date
2018-01-02  368000  370000  360500  360500   92533
2018-01-03  360000  368500  360000  363000   81340
2018-01-04  367500  367500  349000  349000  190391
2018-01-05  351000  352000  348000  351500   99268
2018-01-08  359000  383500  358000  383500  490208

In [29]:
# 행 추가
lotte_che["Return"] = lotte_che["Close"].pct_change().fillna(0)
lotte_che.head()

              Open    High     Low   Close  Volume    Return
Date
2018-01-02  368000  370000  360500  360500   92533  0.000000
2018-01-03  360000  368500  360000  363000   81340  0.006935
2018-01-04  367500  367500  349000  349000  190391 -0.038567
2018-01-05  351000  352000  348000  351500   99268  0.007163
2018-01-08  359000  383500  358000  383500  490208  0.091038

In [31]:
# 열 추가
lotte_che.loc["2021-12-23"] = [100, 200, 300, 400, 500, 600]
lotte_che.tail(1)

            Open  High  Low  Close  Volume  Return
Date
2021-12-23   100   200  300    400     500   600.0

## DataFrame 행과 열 예제

In [32]:
def return_fn(df):
  df_close = df[["Close"]]
  df_close["Return"] = df_close["Close"].pct_change().fillna(0)
  return df_close

In [33]:
res = return_fn(lotte_che_df)
res.head()

/tmp/ipykernel_1920/2648756716.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_close["Return"] = df_close["Close"].pct_change().fillna(0)

             Close    Return
Date
2018-01-02  360500  0.000000
2018-01-03  363000  0.006935
2018-01-04  349000 -0.038567
2018-01-05  351500  0.007163
2018-01-08  383500  0.091038